# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aae22de159fe28bde017e8ccf22f11b167c063374213e332d61d3d3445f30a4fb5b56cf2c29704615bd5e03c7c2a15551fd3d21559bafd613b8144afb49990c1

test:
  secret_key_base: fc0acc9ee8b6dc9708cba5182c64d88d64008159d15bce5412f8a156ca13a0ff356e2efa6fbea74b5dfa2d9749f75d99754b66f3b40fcc0a30b707942389abe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
